### PR TITLE
refactor: remove unnecessary to_string()

### PR DESCRIPTION
**Pull request by murlakatamenka**
aint-much

### CODE REVIEW

**Comment by murlakatamenka** [comment]
@Shinyzenith yeah, no problems here.

While at it, I'll push more commits to fix current `clippy` warnings, CONTRIBUTING.md and `make check` expect clean output.

**Comment by murlakatamenka** [comment]
Okay, it's a beefier PR now and ready to be reviewed.

**Comment by Shinyzenith** [comment]
Hi the pr target needs to be changed to the above mentioned branch.

**Comment by Shinyzenith** [comment]
Also I see you changed the previous commits of the branch which isn't ideal as their signature in the git object store will change.

**Comment by murlakatamenka** [comment]
Yeah, sorry for the fuss.

The order is restored now, the target branch is that feature freeze one.

**Comment by Shinyzenith** [comment]
Thank you for the patch! It's definitely honest work!

**Pull request merged**
