### PR TITLE
chore: when make a big image,loop skip first one

### PR DESCRIPTION
**Pull request by Decodetalkers**
this maybe can make screen overlay a bit faster

### CODE REVIEW

**Comment by Shinyzenith** [comment]
can you rebase against main?

**Comment by Shinyzenith** [comment]
Apart from that, everything else is fine

**Comment by Decodetalkers** [comment]
oh, I have not noticed that

**Review by Shinyzenith — APPROVED** [review]

**Comment by Shinyzenith** [comment]
Merged as: https://github.com/waycrate/wayshot/commit/f404e9d520519df5b268bca66941fa30690d2c96

**Pull request merged**
