### PR TITLE
accounting for directories in file path

### PR DESCRIPTION
**Pull request by rachancheet**
Currently Wayshot save screenshots in the current working directory. However this is not ideal as some users like to save screenshots in a particular directory(For example $HOME/Pictures/screenshots).
This PR introduces a `--folder` flag which allows users to select save directory for their screenshots.

### CODE REVIEW

**Comment by Shinyzenith** [comment]
I believe this can be done with `-f, --file`.

**Comment by rachancheet** [comment]
you will have to manually set a unique file name every time you want to save a screenshot in a directory . Folder flag makes it so you can just specify the folder location and file names are UNIX_TIMESTAMP-wayshot.EXTENSION

**Comment by Shinyzenith** [comment]
I think this is better solved by having file flag accept paths too. That way we can automatically have the same behavior. Introducing too many flags isn't great UX.

**Comment by rachancheet** [comment]
I have added the requested change . Please review .

**Review by Shinyzenith — APPROVED** [review]

**Comment by Shinyzenith** [comment]
CC: @zubairmh @Decodetalkers

**Review by zubairmh — APPROVED** [review]
Aside from some styling changes that can be made, commit is ok

**Comment by Shinyzenith** [comment]
> Aside from some styling changes that can be made, commit is ok

Can you expand on this? Style looks fine to me.

**Review by Decodetalkers — APPROVED** [review]

**Comment by zubairmh** [comment]
> Can you expand on this? Style looks fine to me.

@Shinyzenith 
This section could be rephrased

            if pathbuf.is_dir() {
                pathbuf.push(utils::get_default_file_name(requested_encoding));
                Some(pathbuf)
            } else {
                Some(pathbuf)
            }

to something like

            if pathbuf.is_dir() {
                pathbuf.push(utils::get_default_file_name(requested_encoding));
            }
            Some(pathbuf)
            
might just be feeling picky, either way works

**Comment by zubairmh** [comment]
looks good. lgtm

**Review by Shinyzenith — APPROVED** [review]

**Comment by rachancheet** [comment]
cc @Shinyzenith  fixed.

**Comment by Shinyzenith** [comment]
Hi, I'd like to merge this, can you resolve the conflicts?

**Comment by rachancheet** [comment]
Done. @Shinyzenith

**Comment by Shinyzenith** [comment]
Thanks! However, I redid the entire documentation block to be more concise and easy to read.

**Pull request merged**
