### PR TITLE
Make region, sizing, and positioning data structs reusable

### PR DESCRIPTION
**Pull request by AndreasBackx**
Make region, sizing, and positioning data structs reusable

We use different structs/fields to store the same three types of data everywhere:
- Position (x,y)
- Size (width,height)
- Region(position, size)

This makes it so they all reuse the same information.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/waycrate/wayshot/pull/78).
* __->__ #78
* #77
* #76
* #75
* #72
* #71

### CODE REVIEW

**Review by Shinyzenith — APPROVED** [review]

**Comment by Shinyzenith** [comment]
Changes in commit: https://github.com/waycrate/wayshot/pull/78/commits/1a0dd421b04a114f44a62e6d2c1bc403dc143f1b seems good to me!

**Comment by Shinyzenith** [comment]
This PR stack is good to go for me. The PPM regression seems to exist in master too so I won't be marking that as a blocker for this PR stack.

@AndreasBackx Would you have the time to rebase this PR to some recent changes in libwayshot? there's a merge conflict.

@Decodetalkers This pr is green for me, I'll be merging this soon unless there's any further comments on this.

**Comment by Decodetalkers** [comment]
Ok! Please

**Comment by AndreasBackx** [comment]
Will try to rebase this week and post back. Thanks! :)

**Comment by Shinyzenith** [comment]
Hi @Decodetalkers. Andreas has rebased this pr. Would you mind reviewing it one last time before the merge?

Known issues:

- broken ppm rendering regression which is also available in master, it's not a fault of this pr.
- broken overlay on hyprland, seems to be a layer shell issue of the compositor as it is not present in sway.
- scaling issue that also exists on master branch

**Comment by Decodetalkers** [comment]
Ok, I will try it tomorrow

**Comment by Decodetalkers** [comment]
Emm. the problem scale is not fixed now.. 

and 

```
-s, --slurp <SLURP_ARGS>
```
I do not think now it need any args

**Comment by AndreasBackx** [comment]
@Decodetalkers from what @Shinyzenith says, the scaling issue is also on master? `--slurp <SLURP_ARGS>` is still nice to have because sometimes you want to change how slurp acts. For example you could make ti only select windows by passing some kind of window information. Or I think you can make it select entire screens, stuff like that.

**Comment by Decodetalkers** [comment]
> @Decodetalkers from what @Shinyzenith says, the scaling issue is also on master? `--slurp <SLURP_ARGS>` is still nice to have because sometimes you want to change how slurp acts. For example you could make ti only select windows by passing some kind of window information. Or I think you can make it select entire screens, stuff like that.

Emm, what I concerned is that it will always ask you to select again, so the args will be needless

**Comment by AndreasBackx** [comment]
@Decodetalkers yes, it will ask you to select again. Those are the arguments that will be given to slurp from wayshot, not the output from a slurp call.

**Comment by Decodetalkers** [comment]
> @Decodetalkers yes, it will ask you to select again. Those are the arguments that will be given to slurp from wayshot, not the output from a slurp call.

but you still need to resize the picture to the size of xdgoutput

**Comment by AndreasBackx** [comment]
> but you still need to resize the picture to the size of xdgoutput, and , the args need should be the output of slurp, why select again. I think at first, it should shoot all screens, then use slurp to select and cut the picture, right?

These arguments are given after the freeze has happened. Slurp is called when the screen is frozen. This is how it goes when freeze is enabled:

1. Screenshot of all outputs is taken
2. Screenshot is overlayed
3. `slurp` is called with the arguments passed via `--slurp`.
4. User selects portion of the screen
5. Output of slurp is given to Wayshot and cropped.

**Comment by Decodetalkers** [comment]
> > but you still need to resize the picture to the size of xdgoutput, and , the args need should be the output of slurp, why select again. I think at first, it should shoot all screens, then use slurp to select and cut the picture, right?
> 
> These arguments are given after the freeze has happened. Slurp is called when the screen is frozen. This is how it goes when freeze is enabled:
> 
>     1. Screenshot of all outputs is taken
> 
>     2. Screenshot is overlayed
> 
>     3. `slurp` is called with the arguments passed via `--slurp`.
> 
>     4. User selects portion of the screen
> 
>     5. Output of slurp is given to Wayshot the previously overlaid screenshot is cropped and saved.

**Comment by Shinyzenith** [comment]
I'm a little confused with the slurp interaction. However, that is my fault due to not reading the thread completely. Give me some time.

Maybe a lot of this slurp interaction could be removed by integrating waysip into wayshot. I will do that after #78 is complete.

**Comment by AndreasBackx** [comment]
Technically slurp shouldn't be required, it should be made optional. I think if we plan on integrating waysip, could we land with the issue? As long as we don't tag a new version, that should hopefully be okay?

**Comment by Decodetalkers** [comment]
> Technically slurp shouldn't be required, it should be made optional. I think if we plan on integrating waysip, could we land with the issue? As long as we don't tag a new version, that should hopefully be okay? Otherwise, it's relatively easy to make it optional. We can fix it after landing all of these PRs and maybe have a clearer head.

My main trouble still be, the picture won't be full of the screen when scale is 1.5

**Comment by AndreasBackx** [comment]
@Decodetalkers considering there are also scaling issues on the master branch. Can this be fixed in a later version? This is already a really big change and pushing even more stuff into it is going to make this even harder to land.

**Comment by Decodetalkers** [comment]
> @Decodetalkers considering there are also scaling issues on the master branch. Can this be fixed in a later version? This is already a really big change and pushing even more stuff into it is going to make this even harder to land.

Emm, ok, but another problem is that --slurp still need an arg, but it need to be selected again, so is it designed to this kind? it do not use the area passed by arg, I will glad to make this pr go, but only one I am confused is still this `--slurp`

**Comment by AndreasBackx** [comment]
@Decodetalkers I am having a hard time understanding what you mean exactly. Though `--slurp` is is being used here: https://github.com/waycrate/wayshot/pull/78/files#diff-07c5f12242ede0fe1716dbe6393d6cd3a4eb49b4e440dbfed36a1e4bbc1e0651R76-R91. For some reason it's still required even though it's using an `Option` apparently. Though that was discussed earlier here and on Discord and can be fixed, though likely waysip or some other integration is better.

**Comment by Shinyzenith** [comment]
@AndreasBackx I think it's best to work on the waysip integration in that case, I'd want the scaling issue to land in another patch ( I'll have it taken care of ). Should I go ahead and try to land a patch stack on top of pr78? I'll send a patch over Discord to you if that's fine?

**Comment by Shinyzenith** [comment]
> It's up to you. I'd say it would make everyone's life easier to merge and branch from master afterwards. If we don't roll out a new version in the meantime and iron out more kinks, that should be okay?

I think that would be fine. There are some `-git` users from arch so I'll merge this into a local branch and implement waysip on that branch -- Once it's finalized I can go ahead and merge to master. Does that sound fine with you? This would avoid the constant rebase hell too -- I can avoid merging prs till waysip integration is completed as that has a high priority.

**Review by Shinyzenith — APPROVED** [review]

**Comment by Shinyzenith** [comment]
@Decodetalkers The slurp issue will be tackled by introducing waysip in another branch and merged into master. Apart from scaling and slurp, is everything okay according to you? I'd love to have your approval before going forth with the merge.

**Review by Decodetalkers — APPROVED** [review]

**Comment by Decodetalkers** [comment]
@Shinyzenith can it be merged now?

**Pull request merged**
