### PR TITLE
Current monitor detection

### PR DESCRIPTION
**Pull request by Shinyzenith**

### CODE REVIEW

**Comment by Shinyzenith** [comment]
Can someone with dual monitors test this?

**Comment by Shinyzenith** [comment]
Also, fair warning, I do not know how to work with Option<T>, I kinda winged that part along with some help from rustc. If someone can review the logic then that would be amazing.

**Comment by NikolaTesla13** [comment]
> Can someone with dual monitors test this?

I have two monitors, I'll test it later today when I get home.

**Comment by Shinyzenith** [comment]
> > Can someone with dual monitors test this?
> 
> I have two monitors, I'll test it later today when I get home.

Thank you!

**Comment by Shinyzenith** [comment]
checked rn, this does not work.

**Comment by Shinyzenith** [comment]
XdgOutputHandler always returns is_current even if the monitor is not the one is focus, I guess my understanding of the parameter was flawed to begin with.

**Pull request merged**
